travis:
  secure:
    BINSTAR_TOKEN: EoapIGifwR0vGSElT8vgrKwre0SQTKMP6+37VEO6t0Aj4/X/d4aJA04x98xcoJeqrEwHaec8oAXOBeMPay3yl/je7P0ESSVQOYRyICXL099cSIxhCMqlZ5nXWPqMFvfntDbJZ5BlQ3QznWIWfyIy3JBJnpeGHsZSu8vPVVHFuUrrCgvcVBsv+i4YTazRWKuIitn1xGfcOWf9JbQOji5ccr1/y3T2BNwE+ToCaj4BN187ovaujOGIOU1KYNivWNWQMDt93MX/Sb9+NPw9ifTpehfoBuPhdrXZjLFVUm0jYsnPFrIXPVzpNNGnAdHmQXQi9q1nMvfkeE+gkKiKKVLvbFqeR6m6Afyg2A401sLphNCYUoS8g3q8zNn2QIQnMu3G+Fc7c9zK+b6zuai3fqh2Nb1WkODIpQWAWZY9dDRfn8yr5X4Mis+j5p0ZxuUjptuRnn9F7WZDaVOTCiC89jsw1SgymygQUKE0pE1EiemK2jyL88a+ndUsx1Jv4ieHgUH6Q+NxYSRMhoKHf0WzWlKfZ10pRcFW6C0N1jEBhE2OEJWdpOdLZwFmKiHue3oDOmVtRPce00/yB/b4BpUdMOmZP8Pkimznnkl1uxipxQtZp4laAY0Umc37raXndXKKQqfhE2LeyQjfVKKiunsEa5qAcS5g/DUc+oSJZ2z1lc+SWbI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
